---
params:
  projectdir: !expr here::here() # "~/path/to/project" # Use  when loading. Can also hard code if for some reason you need that
  project_name: "PPAR agonists"        # Change depending on your project name
  clust_method: "spearman" # For clustering
  tree_height_cutoff: 0.1  # For clustering
  dendro_color_by: "group" # Specify how you would like to color the dendrograms
  nmr_threshold: 100000    # 10% of 1M reads for TempOSeq = 100,000; 10% of 10M reads for RNA-Seq = 1,000,000.
  align_threshold: 0.5     # 50% alignment rate for TempO-Seq Experiments
  gini_cutoff: 0.95
  sampledata_sep: ","     # Comma for TempO-Seq, Maybe tabs for RNASeq, customize!
  groups:                  # These should be "interesting" groups for your analysis. Group together for exploring covariation.
    1: ["chemical", "dose", "Time"]
    2: ["I7_Index_ID", "I5_Index_ID"] 
    3: ["row", "column"]
    #4: ["batch"]
    #As many groups as desired...
  batch_var: "Time"          # "batch"
  dose: "dose"               # If there is a dose in the experiment; otherwise use NULL
  treatment_var: "chemical"
  Platform: "TempO-Seq"      # TempO-Seq Or RNA-Seq
  collapse_replicates: F # Set to true if you have replicate flow cells that need to be summed into a single value
  # Column names for metadata, if applicable
  technical_control: "technical_control"
  reference_rna: "reference_rna"
  solvent_control: "solvent_control"
---
