$schema: "http://json-schema.org/draft-07/schema#"
description: snakemake configuration file 
properties:
  genome_filename:
    type: string
    description: filename for genome (in fasta format), e.g. 'GCF_000001635.27_GRCm39_genomic.fna'
  annotation_filename:
    type: string
    description: filename for annotation (in GTF format), e.g. 'GCF_000001635.27_GRCm39_genomic.gtf'
  genome_name:
    type: string
    description: used for labeling genome index files
  seqtype:
    type: string
    description: Experiment type. One of 'rnaseq' or 'temposeq'
  mode:
    type: string
    description: Sequencing mode. One of 'se' (single-end) or 'pe' (paired-end)
  threads:
    type: integer
    default: 1
    description: Number of threads to use, for multi-threaded programs (default 1)

required:
  - genome_filename
  - annotation_filename
  - genome_name
  - seqtype
  - mode